server:
  port: 8096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdbfornotes?createDatabaseIfNotExist=true
    username: root
    password: Sqlrootdre_10102003
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


resilience4j :
  circuitBreaker :
    instances :
      myServiceCircuitBreaker :
        registerHealthIndicator : true
        slidingWindowsSize : 5
        minimumNumberOfCalls : 5
        failureRateThreshold : 80
        waitDurationInOpenState : 10ms
        permittedNumberOfCallsInHalfOpenState : 2
        automaticTransitionFromOpenTOHalfOpenEnabled : true