server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QuotesApplication?createDatabaseIfNotExist=true
    username: root
    password: Sunmisola
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


resilience4j:
  circuitbreaker:
    instances:
      myServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 80
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
